apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: demo
type: Opaque
stringData:
  postgres-password: "password"
  connection-string: "Host=postgres-0.postgres;Database=DeviceDb;Username=postgres;Password=password"
