apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "DeviceDb"
  ASPNETCORE_ENVIRONMENT: "Production"
  DEVICE_REGISTRATION_API_URL: "http://device-registration-api"
