apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-device-registration
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: device-registration-api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: statistics-api
    ports:
    - protocol: TCP
      port: 8080
